apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ci-cd-final-project-pipeline
  namespace: sn-labs-iagigiba
spec:
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string
    - name: build-image
      type: string
  workspaces:
    - name: output
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      runAfter: [cleanup]
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: output

    - name: flake8-lint
      runAfter: [git-clone]
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: output

    - name: nose-tests
      runAfter: [flake8-lint]
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: build-image
      runAfter: [nose-tests]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      runAfter: [build-image]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) \
            --image=$(params.build-image) \
            --dry-run=client -o yaml | oc apply -f -
